### ISSUE TITLE
[Backend] Clear all history

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/shortify#10]
There should be a service that can delete all the generated URLs from the database. The endpoint should be `/api/deleteAll`. Please follow the services already present in the codebase.

**Comment by svnnynior** [comment]
Hello, I would like to work on this, could you assign it to me?

**Comment by rollivier** [comment]
Hi, can you assign this to me ?

**Comment by sprakash57** [comment]
I have assigned it to you.

**Comment by rollivier** [comment]
I just made a PR #13 on this issue.

**Comment by sprakash57** [comment]
PR has been merged. Awesome that you have added test cases as well. Kudos!!

**Comment by rollivier** [comment]
@sprakash57, happy to help ! Hacktoberfest informs me "ineligible repository", can you add the hacktoberfest topic to your repository and hacktoberfest-accepted to my PR ? Thank you !

**Comment by sprakash57** [comment]
Added. Let me know if it has been fixed. Don't forget to star ⭐ this repo, if enjoyed your time here.
