### ISSUE TITLE
[Bug] Text and UI design is not clearly visible in dark mode.

### ISSUE THREAD

**Issue by rollivier** [sprakash57/shortify#14]
When you switch the application to dark, you can no longer read the messages displayed under the input.
The placeholder of the input has a low contrast which makes it difficult to read. 

<img width="1131" alt="light_version" src="https://user-images.githubusercontent.com/10422615/97113275-78836480-16e9-11eb-83af-42f46669bbda.png">

<img width="1131" alt="dark_version" src="https://user-images.githubusercontent.com/10422615/97113279-80430900-16e9-11eb-978e-7b2a7a371b53.png">

@sprakash57 If it suits you, you can assign me and I will take care of correcting them.

**Comment by sprakash57** [comment]
@rollivier Thank you for filing the issue. You have been assigned.

**Comment by rollivier** [comment]
Hi, I just pushed a PR#23 with some optimizations in the dark version.

I couldn't change the color of the placeholder directly in js. So I made an important change in the logic of the Light/dark mode. I removed the style switch in the js to move it directly in the CSS. I think this will make the js more readable and make the application easier to maintain if it gets bigger. Moreover, you can easily manage a dark version of any new component of the application, just by specifying "#app.dark" in the css.  

I hope this suits you 😄 ?

**Comment by sprakash57** [comment]
Well Done. It's a pleasure working with you.
