### ISSUE TITLE
Add Dark and Light theme to the app

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/shortify#2]
There should be a button (maybe a switch would be better) at the top right corner. This will toggle the theme between light and dark mode. Also, make sure shorties'(short URL cards) color scheme should be compatible with dark mode.

**Comment by maw1a** [comment]
Hey, I would like to work on this. Can you assign this issue to me?

**Comment by sprakash57** [comment]
Sure. I have assigned it to you. All the best!!

**Comment by sprakash57** [comment]
Thank you for your contribution. PR has been merged. If you have enjoyed it,  ⭐ the repo would be highly appreciated.
