### ISSUE TITLE
[UI] Integrate vue-fontawesome

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/shortify#22]
Currently, emoticons/text are being used as a placeholder for all icons. The ultimate goal is to standardized the icon system in the app.

- [ ] Add vue-fontawesome library.

**Comment by creativenull** [comment]
Hey! May I give this a try?

**Comment by sprakash57** [comment]
Why not? Assigning it to you. Make sure you implement at least one icon to verify the integration. Maybe you can use icon for "copy" button.

**Comment by creativenull** [comment]
Do you also want icons for the emojis? Like the sleeping (😴) and the tired (😫) emojis? I only found the tired one on fontawesome not the sleeping one, other than that, I found for all of them

**Comment by sprakash57** [comment]
You can skip that for now.

**Comment by creativenull** [comment]
Made the PR, for your review 🙂

**Comment by sprakash57** [comment]
Do give a 🌟 to the repo, if u enjoyed what u just contributed. Looking forward to work with u again.

**Comment by creativenull** [comment]
Likewise 😃
