### ISSUE TITLE
Add OpenAPI spec to Docker web server

### ISSUE THREAD

**Issue by gazconroy** [sprakash57/shortify#31]
Displaying the OpenAPI specification from the ReadMe uses a 'cheeky' workaround. This means you get the vanilla Swagger UI experience including undesirable things like the redundant 'Schemas' panel (already in the endpoint descriptions) and the non-functioning 'Try it out' feature.

By moving the file to the web server, you can use Redoc output (instead of Swagger UI). Since both the Open API specification and Shortify would then be on the same server, you could then implement the 'Try it out' feature (with a hybrid Swagger UI/Redoc solution).

Alternatively, you could use GitHub pages and, say, Jekyll to host the standalone documentation/Redoc html.

**Comment by sprakash57** [comment]
Yeah, let's use Github pages for now.

**Comment by sprakash57** [comment]
OpenAPI docs are live at https://sprakash57.github.io/shortify/server/oas/index.html#operation/post-shorty

thanks @gazconroy.
