### ISSUE TITLE
Update dockerfile and docker-compose

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/shortify#39]
There are a couple of modifications are needed for the docker ecosystem -

- [ ] Dockerfile should be using 14.x `alpine` or `slim` version of node.js.
- [ ] Upgrade docker-compose version to latest. Currently it is 3.7.
- [ ] Hot reloading (through volume mapping) is needed for development.
- [ ] Remove redundant code from Dockerfile and `docker-compose`.

**Comment by biswain2309** [comment]
Could you please assign this issue to me?

**Comment by sprakash57** [comment]
Sure. go ahead @biswain2309

**Comment by biswain2309** [comment]
Updated docker-compose version and replaced docker image build to alpine. Please review.
