### ISSUE TITLE
Add test cases for List component.

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/shortify#4]
One test case is already present. You need to add more test cases into List.spec.ts.

**Comment by silltho** [comment]
I would like to give it a try.

**Comment by sprakash57** [comment]
An earnest request. Please do not raise PR before getting it assigned. The assignment will happen on a first come first serve basis, so you need not to worry.

**Comment by silltho** [comment]
Sorry i noticed it's a small change so i did it right away. Since i have stuff to do the next couple of days and not be able to work on it.
You sound pretty serious? Is there anything worse could have happened than rejecting my PR?
