### ISSUE TITLE
[New feature]URL card should have a delete button.

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/shortify#7]
Right now you can only add a shorty. What if you want to delete one?

Add a button somewhere in the bottom section of an URL card that will remove the card from the list.

**Comment by sprakash57** [comment]
This issue is dependent on #9. Pick it once that is closed.

**Comment by svnnynior** [comment]
I would like to give this a try, could you assign it to me?

**Comment by sprakash57** [comment]
I would love to. But as i mentioned this is dependent on #9 . Without delete service you will only be creating a button. And that doesn't make sense.

**Comment by sprakash57** [comment]
#9 has been closed. This issue can be picked up.

**Comment by svnnynior** [comment]
I'm ready to pick this up now, could you assign it to me?

**Comment by sprakash57** [comment]
You have been assigned.
