### ISSUE TITLE
[New feature] URL card should have copy button.

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/shortify#8]
Currently, you can copy shorties by clicking on them. Now the requirement is to add a copy button, that will copy the generated URL. Points to remember -
- Remove `https` while displaying the shorties in the card.
- While someone clicking on the `copy` button, append the `https` prefix.

**Comment by svnnynior** [comment]
Hello, I would like to work on this, could you assign it to me?

**Comment by sprakash57** [comment]
Sure, assigned.
