### ISSUE TITLE
[Backend] Create a delete url service

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/shortify#9]
The endpoint should be `/api/delete/:id`. Get and Create services are already there please follow coding standards as per the structure given.

**Comment by smsriharsha** [comment]
can you assign this to me

**Comment by sprakash57** [comment]
@smsriharsha Sure. You can work on this.

**Comment by qsingletary** [comment]
@sprakash57 I could grab this one. Can you assign it to me?

**Comment by sprakash57** [comment]
Sure. Go ahead.

**Comment by sprakash57** [comment]
@qsingletary mate r you still working on it?

**Comment by qsingletary** [comment]
@sprakash57 I’m wrapped up, I will push my PR this morning for you 👍
